### ISSUE TITLE
ConfigProps class code still missing somethink not checked-In

### ISSUE THREAD

**Issue by avmgan** [hakdogan/ElasticSearch#2]
Hello Hakdogan,

Thanks for your elasticsearch code reference, I'm playing around with your elasticsearch project code. seems to be some of the class methods are not exist, not compiling seems to be not checked-in.

Following method properties missing on this class ConfigProps
props.getIndex().getName()
props.getIndex().getType()
props.getRestClient().getHostname()
props.getRestClient().getPort()
props.getRestClient().getScheme()

log class initialize missing on QueryDAO class

**Comment by hakdogan** [comment]
Hi @avmgan,

I used [lombok](https://projectlombok.org) this project. You don't have to write getters, setters also constructors with this library. The library has various plugin for IDE's.
